### PR TITLE
update for C++14

### PR DESCRIPTION
**Pull request by bgoodri**
This PR allows your package to build with rstan 2.18.1 on CRAN, which requires C++14. I have run R CMD check on your package from a Debian system similar to that on CRAN and uploaded the tarball to https://win-builder.r-project.org/ so the package maintainer should soon see the result of running R CMD check on Windows.

If you have questions or issues, please post at
https://discourse.mc-stan.org/t/how-to-update-a-package-that-has-stanheaders-and-rstan-in-its-linkingto/6041?u=bgoodri
rather than, or in addition to, this PR so that other maintainers of R packages that use Stan can benefit from your experience.

If all goes well with the R CMD check, please upload a new version to CRAN soon before your package gets kicked out.

### CODE REVIEW

**Comment by bgoodri** [comment]
This got merged and then subsequently the C++14 thing got taken out. Now it is blocking the upload of StanHeaders 2.19 to CRAN because running `R CMD check` on glmmfields yields the error

> /opt/r-devel/library/StanHeaders/include/stan/math/rev/mat/functor/adj_jac_apply.hpp:31:54: note: deduced return type only available with -std=c++14 or -std=gnu++14
/opt/r-devel/library/StanHeaders/include/stan/math/rev/mat/functor/adj_jac_apply.hpp:48:48: error: ‘apply’ function uses ‘auto’ type specifier without trailing return type
 constexpr auto apply(const F& f, const Tuple& t) {
                                                ^

**Comment by seananderson** [comment]
Apologies, that got lost while we were attempting to make the package compliant with staged installation on CRAN. I have switched it back to C++14, am running checks right now, and then will submit to CRAN immediately.

**Comment by seananderson** [comment]
I submitted an update to CRAN earlier today that uses C++14.
